import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Product() {

  const { query } = useRouter()
  const productId = query.id

  return (
    <>
      <Head>
        <title>Nome do Produto - Ignite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <h1>Produto: {productId}</h1>
      </main>
    </>
  )
}