import Head from 'next/head'
import { useKeenSlider } from 'keen-slider/react'

import { HomeContainer } from '@/components/Home/HomeContainer'
import { ProductItem } from '@/components/Home/ProductItem'

import 'keen-slider/keen-slider.min.css'
import { stripe } from '@/lib/stripe'
import { GetStaticProps } from 'next'
import Stripe from 'stripe'


export const getStaticProps: GetStaticProps = async () => {
  const response = await stripe.products.list({
    expand: ['data.default_price']
  })

  const products = response.data.map( product => {

    const price = product.default_price as Stripe.Price

    return {
      id: product.id,
      name: product.name,
      imageUrl: product.images[0],
      description: product.description,
      price: new Intl.NumberFormat('pt-BR', {
        style: 'currency',
        currency: 'BRL'
      }).format(price.unit_amount?  price.unit_amount / 100 : 0)
    }
  })

  return {
    props: {
      products
    },
    revalidate: 60 * 60 * 2 // 2 hours
  }
}

interface HomeProps {
  products: {
    id: string,
    name: string,
    imageUrl: string,
    description: string,
    price: string
  }[]
}

export default function Home( {products}: HomeProps ) {

  const [slideRef] = useKeenSlider({
    slides: {
      perView: 2.5,
      spacing: 48,
    },
    drag: true
  })

  return (
    <>
      <Head>
        <title>Ignite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      
      <main>
        <HomeContainer ref={slideRef} className='keen-slider' data-keen-slider-scrollable>

          {products.map( (product) => {
            return (
              <ProductItem key={product.id} className='keen-slider__slide' product={product} />
            )
          } )}

        </HomeContainer>
      </main>
    </>
  )
}

