import { Success } from '@/components/Success/Success'
import { stripe } from '@/lib/stripe'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Stripe from 'stripe'


export const getServerSideProps: GetServerSideProps = async ({query}) => {
  
  if ( !query.session_id ){
    return {
      redirect: {destination: '/',
      permanent: false,
      }
    }
  }

  const sessionId = String(query.session_id)

  const session = await stripe.checkout.sessions.retrieve(sessionId, {
    expand: ['line_items', 'line_items.data.price.product']
  })

  const customerName = session.customer_details?.name
  const product = session.line_items?.data[0].price?.product as Stripe.Product

  return {
    props: {
      product: {
        imageUrl: product.images[0],
        name: product.name
      },
      customerName
    }
  }
}

interface SuccessProps {
  product: {
    imageUrl: string
    name: string
  },
  customerName: string
}


export default function SuccessPage({product, customerName}: SuccessProps) {
  return (
    <>
      <Head>
        <title>Sucesso - Ignite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      
      <main>
        <Success product={product} customerName={customerName}/>
      </main>
    </>
  )
}