import Head from 'next/head'

export default function Success() {
  return (
    <>
      <Head>
        <title>Sucesso - Ignite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <h1>Sucesso</h1>
      </main>
    </>
  )
}